/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import ApplicationClasses.DbConnect;
import java.lang.String;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author HaNi
 */
public class cheque extends javax.swing.JFrame {

    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public static boolean check22 = true;
    
    
    
    /**
     * Creates new form cheque
     */
    public cheque() {
        initComponents();
        
        con = DbConnect.connect();
        tableload2();
        
        
    }
    
    
    
    
    
    public cheque(String name,String branch,String info,String code,String rout,String acno,String che,String no,String camo,String cdate,String des,String status){
         initComponents();
                SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
                
                jtbkname.setText(name);
                jtbra.setText(branch);
                jtinfo.setText(info);
                jtcode.setText(code);
                jtrout.setText(rout);
                jtacno.setText(acno);
                jtche.setText(che);
                jtno.setText(no);
                jtcamo.setText(camo);
                
               // if(!main.chh)
        {
            jBchequeAdd.setEnabled(false);
        }
                
        try {
            dcdate.setDate(formatDate.parse(cdate));
            
        } catch (ParseException ex) {
            Logger.getLogger(cheque.class.getName()).log(Level.SEVERE, null, ex);
        }
                jtdes.setText(des);
                if(status.equalsIgnoreCase("Bounce")){
                    jcbo.setSelected(true);
                }
                else if (status.equalsIgnoreCase("Realise")){
                jcre.setSelected(true);
                }else
                jcpen.setSelected(true);
                
                
                con = DbConnect.connect();
                tableload2();
    }
    
    
 public void tableload2()
    {
        try
        {
           String sql = "SELECT * from cheque";
          
            pst = con.prepareStatement(sql); 
            rs = pst.executeQuery();
            
            jtcheque.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } 
        catch (Exception e)
        {
        }
        
        
    }
 
 
 public void clearFields(){
 
                jtbkname.setText(null);
                jtbra.setText(null);
                jtinfo.setText(null);
                jtcode.setText(null);
                jtrout.setText(null);
                jtacno.setText(null);
                jtche.setText(null);
                jtno.setText(null);
                jtcamo.setText(null);
                dcdate.setDate(null);
                jtdes.setText(null);
                buttonGroup1.clearSelection();
               
                
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jtbkname = new javax.swing.JTextField();
        jtbra = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtinfo = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jtche = new javax.swing.JTextField();
        jtno = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jtcamo = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtdes = new javax.swing.JTextArea();
        jtacno = new javax.swing.JTextField();
        jtcode = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtcheque = new javax.swing.JTable();
        jBchequeAdd = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jcbo = new javax.swing.JCheckBox();
        jtrout = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jcpen = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        dcdate = new com.toedter.calendar.JDateChooser();
        jcre = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Bank Information");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 32, -1, -1));

        jLabel34.setText("Bank Name");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 76, -1, -1));

        jLabel35.setText("Branch");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 114, -1, -1));

        jtbkname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbknameActionPerformed(evt);
            }
        });
        jtbkname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbknameKeyReleased(evt);
            }
        });
        getContentPane().add(jtbkname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 73, 290, -1));

        jtbra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbraActionPerformed(evt);
            }
        });
        jtbra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbraKeyReleased(evt);
            }
        });
        getContentPane().add(jtbra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 111, 290, -1));

        jLabel36.setText("Information :");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 149, -1, -1));

        jtinfo.setColumns(20);
        jtinfo.setRows(5);
        jtinfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtinfoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtinfoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtinfo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 149, 290, -1));

        jLabel40.setText("Cheque No : ");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 76, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setText("Cheque Information");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 32, -1, -1));

        jtche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcheActionPerformed(evt);
            }
        });
        jtche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtcheKeyReleased(evt);
            }
        });
        getContentPane().add(jtche, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 73, 300, -1));

        jtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnoActionPerformed(evt);
            }
        });
        jtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtnoKeyReleased(evt);
            }
        });
        getContentPane().add(jtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 111, 300, -1));

        jLabel42.setText(" No :");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 114, -1, -1));

        jLabel44.setText("Amount : ");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 152, 60, -1));

        jtcamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcamoActionPerformed(evt);
            }
        });
        jtcamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtcamoKeyReleased(evt);
            }
        });
        getContentPane().add(jtcamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 149, 300, -1));

        jLabel45.setText("Date :");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 193, -1, -1));

        jLabel43.setText("Description :");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 225, 75, -1));

        jtdes.setColumns(20);
        jtdes.setRows(5);
        jScrollPane4.setViewportView(jtdes);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 225, 302, -1));

        jtacno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtacnoActionPerformed(evt);
            }
        });
        jtacno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtacnoKeyReleased(evt);
            }
        });
        getContentPane().add(jtacno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 290, -1));

        jtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodeActionPerformed(evt);
            }
        });
        jtcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtcodeKeyReleased(evt);
            }
        });
        getContentPane().add(jtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 290, -1));

        jLabel37.setText(" Transite Code :");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 258, 100, -1));

        jLabel38.setText("Routing No : ");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 20));

        jLabel39.setText("   Account No :");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, 20));

        jtcheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtcheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtchequeMouseClicked(evt);
            }
        });
        jtcheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtchequeKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(jtcheque);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 1030, 230));

        jBchequeAdd.setText("Add");
        jBchequeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBchequeAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBchequeAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, 90, 35));

        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 90, 35));

        buttonGroup1.add(jcbo);
        jcbo.setText("Bounce");
        getContentPane().add(jcbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        jtrout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtroutActionPerformed(evt);
            }
        });
        jtrout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtroutKeyReleased(evt);
            }
        });
        getContentPane().add(jtrout, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 290, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 90, 30));

        buttonGroup1.add(jcpen);
        jcpen.setText("Pending");
        getContentPane().add(jcpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, -1, -1));

        jLabel1.setText("Status : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));
        getContentPane().add(dcdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 290, -1));

        buttonGroup1.add(jcre);
        jcre.setText("Realise");
        getContentPane().add(jcre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbknameActionPerformed
        jtbra.grabFocus();
    }//GEN-LAST:event_jtbknameActionPerformed

    private void jtbknameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbknameKeyReleased
        int count = 0;
        String checkname = jtbkname.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

                JOptionPane.showMessageDialog(null, "cannot have numbers", "Error", WIDTH);
                jtbkname.setText("");

            }
            else if(Character.isLetter(c))
            {

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtbkname.setText("");

            }

        }
    }//GEN-LAST:event_jtbknameKeyReleased

    private void jtbraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbraActionPerformed
        jtinfo.grabFocus();
    }//GEN-LAST:event_jtbraActionPerformed

    private void jtbraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbraKeyReleased
        int count = 0;
        String checkname = jtbra.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

                JOptionPane.showMessageDialog(null, "cannot have numbers", "Error", WIDTH);
                jtbra.setText("");

            }
            else if(Character.isLetter(c))
            {

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtbra.setText("");

            }

        }
    }//GEN-LAST:event_jtbraKeyReleased

    private void jtinfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtinfoKeyPressed
        // jtcode.grabFocus();
    }//GEN-LAST:event_jtinfoKeyPressed

    private void jtinfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtinfoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtinfoKeyReleased

    private void jtcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcheActionPerformed
        jtno.grabFocus();
    }//GEN-LAST:event_jtcheActionPerformed

    private void jtcheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcheKeyReleased
      String che = jtche.getText();
      jtno.setText(che+" : "+jtrout.getText()+" : "+jtacno.getText());
        
        int count = 0;
        String checkname = jtche.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtche.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtche.setText("");

            }

        }
    }//GEN-LAST:event_jtcheKeyReleased

    private void jtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnoActionPerformed
        jtcamo.grabFocus();
    }//GEN-LAST:event_jtnoActionPerformed

    private void jtnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtnoKeyReleased
        int count = 0;
        String checkname = jtno.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtno.setText("");

            }

        }
    }//GEN-LAST:event_jtnoKeyReleased

    private void jtcamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcamoActionPerformed
        dcdate.grabFocus();
    }//GEN-LAST:event_jtcamoActionPerformed

    private void jtcamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcamoKeyReleased
        int count = 0;
        String checkname = jtcamo.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtcamo.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtcamo.setText("");

            }

        }
    }//GEN-LAST:event_jtcamoKeyReleased

    private void jtacnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtacnoActionPerformed
        jtche.grabFocus();
    }//GEN-LAST:event_jtacnoActionPerformed

    private void jtacnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtacnoKeyReleased
        String act = jtacno.getText();
      jtno.setText(jtche.getText()+" : "+jtrout.getText()+" : "+act);
        
        
        int count = 0;
        String checkname = jtacno.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtacno.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtacno.setText("");

            }

        }
    }//GEN-LAST:event_jtacnoKeyReleased

    private void jtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodeActionPerformed
        jtrout.grabFocus();
    }//GEN-LAST:event_jtcodeActionPerformed

    private void jtcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcodeKeyReleased
        
        
        
        
        
        int count = 0;
       String checkname = jtcode.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtcode.setText("");

            }

        }
    }//GEN-LAST:event_jtcodeKeyReleased

    private void jBchequeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBchequeAddActionPerformed
      
       
        
        String bkname = jtbkname.getText();
        String bra = jtbra.getText();
        String info = jtinfo.getText();
        String code = jtcode.getText();
        String rout = jtrout.getText();
        String acno = jtacno.getText();
        String cid = jtche.getText();
        String no = jtno.getText();
        String camo = jtcamo.getText();
        Date date = dcdate.getDate();
        String des = jtdes.getText();
        
        
        String check = null;
        
        if (jcre.isSelected()) {

            check = "Realise";

        } else if (jcbo.isSelected()){

            check = "Bounce";

        }
        else {
            check= "Pending";
        }
 
 
    try
    {
        
    SimpleDateFormat sdfFrom = new SimpleDateFormat("yyyy-MM-dd");
 String strDate = sdfFrom.format(date);
       if (bkname.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Bank Name field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (bra.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Branch field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (info.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Information field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (code.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Transit Code field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (rout.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Routing No field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (acno.isEmpty())
        {

           JOptionPane.showMessageDialog(null, "Please Fill the Account No field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (cid.isEmpty())
        {

           JOptionPane.showMessageDialog(null, "Please Fill the Cheque No field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (no.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the No field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }

        else if (camo.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Amount field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }
        /*else if (per.getCalendar())
        {

            java.awt.Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Select Date..!!!","error",0);
        }*/
        else if (des.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please Fill the Description field  ", "Field is empty",JOptionPane.WARNING_MESSAGE);
        }
        else if (check.isEmpty())
        {

            JOptionPane.showMessageDialog(null, "Please select a Status", "Field not selected",JOptionPane.WARNING_MESSAGE);
        }
        

        else{
            try
            {

                String q = "INSERT INTO cheque (BankName,Branch,Information,TransitCode,RoutingNo,AccountNo,ChequeNo,No,Amount,Date,Description,Status) values ('"+ bkname +"' , '"+ bra +"' , '"+ info +"' , '"+ code +"' , '"+ rout +"' , '"+ acno +"' ,'"+ cid +"',  '"+ no +"', '"+ camo +"', '"+ strDate +"', '"+ des +"',  '"+ check +"')";
                pst = con.prepareStatement(q);
                pst.execute();
                tableload2();
                
                tableload2();
                JOptionPane.showMessageDialog(null, "Saved");
            }
            catch (Exception e)
            {
                System.out.print(e);

            }
            clearFields();
        }
    }
    catch(NullPointerException E)
    {
        JOptionPane.showMessageDialog(null, "Date field cannot be empty and \nshould be in date format", "Field Empty or Input mismatch",JOptionPane.WARNING_MESSAGE);
        
    }
    }//GEN-LAST:event_jBchequeAddActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        
        
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update....?");
          
         

        if(x==0)
        {
            
            String bkname = jtbkname.getText();
            String bra = jtbra.getText();
            String info = jtinfo.getText();
            String code = jtcode.getText();
            String rout = jtrout.getText();
            String acno = jtacno.getText();
            String cid = jtche.getText();
            String no = jtno.getText();
            String camo = jtcamo.getText();
            Date date = dcdate.getDate();
             SimpleDateFormat sdfFrom = new SimpleDateFormat("yyyy-MM-dd");
 String strDate = sdfFrom.format(date);
            String des = jtdes.getText();
            String check = null;
            
             if (jcre.isSelected()) {

            check = "Realise";

        } else if (jcbo.isSelected()){

            check = "Bounce";

        }
        else {
            check= "Pending";
        }
             System.out.println(date);
            String sql = "UPDATE cheque SET BankName = '"+ bkname +"' , Branch = '"+ bra +"' , Information = '"+ info +"' , TransitCode = '"+ code +"' , RoutingNo = '"+ rout +"',AccountNo = '"+ acno +"',  ChequeNo = '"+ cid +"' , No = '"+ no +"',Amount = '"+ camo +"', Date = '"+ strDate +"' , Description = '"+ des +"',Status = '"+ check +"' where ChequeNo = '"+ cid +"'";

            try
            {

                pst = con.prepareStatement(sql);
                pst.execute();

                tableload2();
                clearFields();

            }
            catch (Exception e)
            {
                System.out.print(e);
            }

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtroutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtroutKeyReleased
          String rout = jtrout.getText();
      jtno.setText(jtche.getText()+" : "+rout+" : "+jtacno.getText());
        
        int count = 0;
        String checkname = jtrout.getText();

        for (int i = 0; i < checkname.length(); i++) {
            char c = checkname.charAt(i);
            if (Character.isDigit(c)) {

            }
            else if(Character.isLetter(c))
            {
                JOptionPane.showMessageDialog(null, "cannot have letters", "Error", WIDTH);
                jtrout.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(null, "cannot have Special Characters", "Error", WIDTH);
                jtrout.setText("");

            }

        }
    }//GEN-LAST:event_jtroutKeyReleased

    private void jtroutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtroutActionPerformed
       jtacno.grabFocus();
    }//GEN-LAST:event_jtroutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      
        
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtchequeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtchequeKeyPressed
        
    }//GEN-LAST:event_jtchequeKeyPressed

    private void jtchequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtchequeMouseClicked
         int row = jtcheque.getSelectedRow();

        String bkname = jtcheque.getValueAt(row, 0).toString();
        String bra = jtcheque.getValueAt(row, 1).toString();
        String info = jtcheque.getValueAt(row, 2).toString();
        String code = jtcheque.getValueAt(row, 3).toString();
        String rout = jtcheque.getValueAt(row, 4).toString();
        String accno = jtcheque.getValueAt(row, 5).toString();
        String cid = jtcheque.getValueAt(row, 6).toString();
        String no = jtcheque.getValueAt(row, 7).toString();
        String amo = jtcheque.getValueAt(row, 8).toString();
        //  JOptionPane.showMessageDialog(rootPane,jtcheque.getValueAt(row, 5) );
        Date d = (Date) jtcheque.getValueAt(row, 9);
        String des = jtcheque.getValueAt(row, 10).toString();
        String stat = jtcheque.getValueAt(row, 11).toString();
        if(stat.equals("Realise")){
        jcre.setSelected(true);
        }
        else if(stat.equals("Bounce")){
        jcbo.setSelected(true);
        }
        else {
        jcpen.setSelected(true);
        }
        jtbkname.setText(bkname);
        jtbra.setText(bra);
        jtinfo.setText(info);
        jtcode.setText(code);
        jtrout.setText(rout);
        jtacno.setText(accno);
        jtche.setText(cid);
        jtno.setText(no);
        jtcamo.setText(amo);
        dcdate.setDate(d);
        jtdes.setText(des);
       /* String status=null;
        if(status.equalsIgnoreCase("Bounce")){
                    jcbo.setSelected(true);
                }
                else if (status.equalsIgnoreCase("Realise")){
                jcre.setSelected(true);
                }else
                jcpen.setSelected(true);*/
        
    }//GEN-LAST:event_jtchequeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.ButtonGroup buttonGroup3;
    public static com.toedter.calendar.JDateChooser dcdate;
    public static javax.swing.JButton jBchequeAdd;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton11;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel33;
    public static javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel35;
    public static javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel37;
    public static javax.swing.JLabel jLabel38;
    public static javax.swing.JLabel jLabel39;
    public static javax.swing.JLabel jLabel40;
    public static javax.swing.JLabel jLabel41;
    public static javax.swing.JLabel jLabel42;
    public static javax.swing.JLabel jLabel43;
    public static javax.swing.JLabel jLabel44;
    public static javax.swing.JLabel jLabel45;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JCheckBox jcbo;
    public static javax.swing.JCheckBox jcpen;
    public static javax.swing.JCheckBox jcre;
    public static javax.swing.JTextField jtacno;
    public static javax.swing.JTextField jtbkname;
    public static javax.swing.JTextField jtbra;
    public static javax.swing.JTextField jtcamo;
    public static javax.swing.JTextField jtche;
    public static javax.swing.JTable jtcheque;
    public static javax.swing.JTextField jtcode;
    public static javax.swing.JTextArea jtdes;
    public static javax.swing.JTextArea jtinfo;
    public static javax.swing.JTextField jtno;
    public static javax.swing.JTextField jtrout;
    // End of variables declaration//GEN-END:variables
}
